if (NOT VISTA_BUILD_KERNEL)
  message(FATAL_ERROR "VistaDemo cannot be built - VistaCoreLibs component VistaKernel is not activated")
endif ()

include_directories(${CMAKE_SOURCE_DIR}/VistaCoreLibs)

add_subdirectory(01KeyboardDemo)
add_subdirectory(02GeometryDemo)
add_subdirectory(03TextDemo)
add_subdirectory(04LoadDemo)
add_subdirectory(05InteractionDemo)
add_subdirectory(06CameraControlDemo)
add_subdirectory(07OverlayDemo)
add_subdirectory(09EventDemo)
add_subdirectory(10DisplayDemo)
add_subdirectory(11OGLDemo)
add_subdirectory(12IntentionSelectDemo)
add_subdirectory(13KernelOpenSGExtDemo)
add_subdirectory(14DataFlowNetDemo)

option(VISTA_BUILD_15VTKDEMO "" OFF)
if (VISTA_BUILD_15VTKDEMO)
  add_subdirectory(15VtkDemo)
endif ()

option(VISTA_BUILD_16PHANTOMDEMO "" OFF)
if (VISTA_BUILD_16PHANTOMDEMO)
  add_subdirectory(16PhantomDemo OFF)
endif ()

add_subdirectory(17MsgPortDemo)
add_subdirectory(18DebuggingToolsDemo)
add_subdirectory(19TimeDemo)
add_subdirectory(21ClusterModeDemo)
add_subdirectory(22RecordReplayDemo)
