

include( FindPackageHandleStandardArgs )
include( VistaFindUtils )

if( NOT WIN32 )
	message( ERROR "FindVOculusSDK not adjusted for non-linux builds - please adjust it" )
endif()

if( NOT VOCULUSSDK_FOUND )
	vista_find_package_root( OculusSDK LibOVR/Include/OVR_CAPI.h )

	if( OCULUSSDK_ROOT_DIR )
		
		#determine version
		if( EXISTS "${OCULUSSDK_ROOT_DIR}/LibOVRKernel" )
			if( EXISTS "${OCULUSSDK_ROOT_DIR}/LibOVR/Include/OVR_ErrorCode.h" )
				set( _IS_OCULUS_V05PLUS FALSE )
				set( _IS_OCULUS_V1PLUS TRUE )
			else()
				set( _IS_OCULUS_V05PLUS TRUE )
				set( _IS_OCULUS_V1PLUS FALSE )
			endif()			
		else()
			set( _IS_OCULUS_V05PLUS FALSE )
			set( _IS_OCULUS_V1PLUS FALSE )
		endif()

		if( _IS_OCULUS_V1PLUS )
				
			if( MSVC10 )
				set( _MSVC_POSTFIX "VS2010" )
			elseif( MSVC11 )
				set( _MSVC_POSTFIX "VS2012" )
			elseif( MSVC12 )
				set( _MSVC_POSTFIX "VS2013" )
			elseif( MSVC14 )
				set( _MSVC_POSTFIX "VS2015" )
			else()
				message( WARNING "OculusSDK not available for this msvc version" )
			endif()
		
			set( OCULUSSDK_INCLUDE_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Include" )
			if( VISTA_64BIT )
				set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Windows/x64/Release/${_MSVC_POSTFIX}" )
			else()
				set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Windows/Win32/Release/${_MSVC_POSTFIX}" )
			endif()		
			set( OCULUSSDK_LIBRARIES "LibOVR" )
		elseif( _IS_OCULUS_V05PLUS )
		
			set( OCULUSSDK_INCLUDE_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Include" "${OCULUSSDK_ROOT_DIR}/LibOVRKernel/Src" )
			
			if( VISTA_64BIT )
				set( _OCULUS_PREFIX "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Windows/x64" )
			else()
				set( _OCULUS_PREFIX "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Windows/Win32" )
			endif()				
			
			if( MSVC10 )
				set( _MSVC_POSTFIX "VS2010" )
			elseif( MSVC11 )
				set( _MSVC_POSTFIX "VS2012" )
			elseif( MSVC12 )
				set( _MSVC_POSTFIX "VS2013" )
			elseif( MSVC14 )
				set( _MSVC_POSTFIX "VS2015" )
			else()
				message( WARNING "OculusSDK not available for this msvc version" )
			endif()
			
			find_library( OCULUS_LIBRARY_DEBUG libOVR PATHS "${_OCULUS_PREFIX}/Debug/${_MSVC_POSTFIX}" NO_DEFAULT_PATH )
			find_library( OCULUS_LIBRARY_RELEASE libOVR PATHS "${_OCULUS_PREFIX}/Release/${_MSVC_POSTFIX}" NO_DEFAULT_PATH )
			set( OCULUSSDK_LIBRARIES debug "${OCULUS_LIBRARY_DEBUG}" optimized "${OCULUS_LIBRARY_RELEASE}" )
			
		else()
		
			set( OCULUSSDK_INCLUDE_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Include" "${OCULUSSDK_ROOT_DIR}/3rdParty/glext" )
			if( VISTA_64BIT )
					if( MSVC10 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/x64/VS2010" )
				elseif( MSVC11 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/x64/VS2012" )
				elseif( MSVC12 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/x64/VS2013" )
				else()
					message( WARNING "OculusSDK not available for this msvc version" )
				endif()
				set( OCULUSSDK_LIBRARIES optimized libovr64 debug libovr64d )
			else()
				if( MSVC10 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Win32/VS2010" )
				elseif( MSVC11 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Win32/VS2012" )
				elseif( MSVC12 )
					set( OCULUSSDK_LIBRARY_DIRS "${OCULUSSDK_ROOT_DIR}/LibOVR/Lib/Win32/VS2013" )
				else()
					message( WARNING "OculusSDK not available for this msvc version" )
				endif()
				set( OCULUSSDK_LIBRARIES optimized libovr debug libovrd )
			endif()		
		endif()
	endif()
endif()

find_package_handle_standard_args( VOculusSDK "OculusSDK could not be found" OCULUSSDK_ROOT_DIR OCULUSSDK_LIBRARIES )

