if (VISTACORELIBS_USE_GLUT_WINDOWIMP)
  add_subdirectory(VistaGlutMouseDriver)
  add_subdirectory(VistaGlutKeyboardDriver)
  add_subdirectory(VistaGlutJoystickDriver)
endif ()

if (VISTACORELIBS_USE_SDL2_WINDOWIMP)
  add_subdirectory(VistaSDL2MouseDriver)
  add_subdirectory(VistaSDL2RawKeyboardDriver)
  add_subdirectory(VistaSDL2EventKeyboardDriver)
  add_subdirectory(VistaSDL2TextInputDriver)
  add_subdirectory(VistaSDL2ControllerDriver)
endif ()

option(VISTA_DRIVERS_CYBERGLOVE "" ON)
if (VISTA_DRIVERS_CYBERGLOVE)
  add_subdirectory(VistaCyberGloveDriver)
endif ()

option(VISTA_DRIVERS_DTRACK "" ON)
if (VISTA_DRIVERS_DTRACK)
  add_subdirectory(VistaDTrackDriver)
endif ()

option(VISTA_DRIVERS_FASTRAK "" ON)
if (VISTA_DRIVERS_FASTRAK)
  add_subdirectory(VistaFastrakDriver)
endif ()

option(VISTA_DRIVERS_HID "" ON)
if (VISTA_DRIVERS_HID)
  add_subdirectory(VistaHIDDriver)
endif ()

option(VISTA_DRIVERS_IRMAN "" ON)
if (VISTA_DRIVERS_IRMAN)
  add_subdirectory(VistaIRManDriver)
endif ()

option(VISTA_DRIVERS_MIDI "" ON)
if (VISTA_DRIVERS_MIDI)
  add_subdirectory(VistaMIDIDriver)
endif ()

option(VISTA_DRIVERS_PHANTOMSERVER "" ON)
if (VISTA_DRIVERS_PHANTOMSERVER)
  add_subdirectory(VistaPhantomServerDriver)
endif ()

option(VISTA_DRIVERS_HAPTICDEVICEEMULATOR "" ON)
if (VISTA_DRIVERS_HAPTICDEVICEEMULATOR)
  add_subdirectory(VistaHapticDeviceEmulatorDriver)
endif ()

option(VISTA_DRIVERS_SPACEMOUSE "" ON)
if (VISTA_DRIVERS_SPACEMOUSE)
  add_subdirectory(VistaSpaceMouseDriver)
endif ()

# 3rd party libraries needed for: (so they are marked OFF by default)
option(VISTA_DRIVERS_3DCSPACENAVIGATOR "" OFF)
if (VISTA_DRIVERS_3DCSPACENAVIGATOR)
  add_subdirectory(Vista3DCSpaceNavigatorDriver)
endif ()

option(VISTA_DRIVERS_LEAPMOTION "" OFF)
if (VISTA_DRIVERS_LEAPMOTION)
  add_subdirectory(VistaLeapMotionDriver)
endif ()

option(VISTA_DRIVERS_OPENALRECORD "" OFF)
if (VISTA_DRIVERS_OPENALRECORD)
  add_subdirectory(VistaOpenALRecordDriver)
endif ()

option(VISTA_DRIVERS_OPENCVCAPTURE "" OFF)
if (VISTA_DRIVERS_OPENCVCAPTURE)
  add_subdirectory(VistaOpenCVCaptureDriver)
endif ()

option(VISTA_DRIVERS_OPENCVFACETRACK "" OFF)
if (VISTA_DRIVERS_OPENCVFACETRACK)
  add_subdirectory(VistaOpenCVFaceTrackDriver)
endif ()

option(VISTA_DRIVERS_OPENNI "" OFF)
if (VISTA_DRIVERS_OPENNI)
  add_subdirectory(VistaOpenNIDriver)
endif ()

option(VISTA_DRIVERS_OPENVR "" OFF)
if (VISTA_DRIVERS_OPENVR)
  add_subdirectory(VistaOpenVRDriver)
endif ()

option(VISTA_DRIVERS_OPTITRACK "" OFF)
if (VISTA_DRIVERS_OPTITRACK)
  add_subdirectory(VistaOptitrackDriver)
endif ()

option(VISTA_DRIVERS_DEPTHSENSE "" OFF)
if (VISTA_DRIVERS_DEPTHSENSE)
  add_subdirectory(VistaDepthSenseDriver)
endif ()

option(VISTA_DRIVERS_PHANTOM "" OFF)
if (VISTA_DRIVERS_PHANTOM)
  add_subdirectory(VistaPhantomDriver)
endif ()

option(VISTA_DRIVERS_SIXENSE "" OFF)
if (VISTA_DRIVERS_SIXENSE)
  add_subdirectory(VistaSixenseDriver)
endif ()

option(VISTA_DRIVERS_VRPN "" OFF)
if (VISTA_DRIVERS_VRPN)
  add_subdirectory(VistaVRPNDriver)
endif ()

option(VISTA_DRIVERS_WIIMOTE "" OFF)
if (VISTA_DRIVERS_WIIMOTE)
  add_subdirectory(VistaWiimoteDriver)
endif ()

option(VISTA_DRIVERS_CHAI3DHAPTICDEVICES "" OFF)
if (VISTA_DRIVERS_CHAI3DHAPTICDEVICES)
  add_subdirectory(VistaCHAI3DHapticDevicesDriver)
endif ()

if (UNIX)
  option(VISTA_DRIVERS_JSWJOYSTICK "" OFF)
  if (VISTA_DRIVERS_JSWJOYSTICK)
    add_subdirectory(VistaJswJoystickDriver)
  endif ()
elseif (WIN32)
  option(VISTA_DRIVERS_DIRECTXGAMEPAD "" ON)
  if (VISTA_DRIVERS_DIRECTXGAMEPAD)
    add_subdirectory(VistaDirectXGamepadDriver)
  endif ()
endif (UNIX)
